<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY87xbM1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY87xbM1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY87xbM1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY87xbM1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY87xbM1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y87xbM1',
    'container.build_id' => '0e051346',
    'container.build_time' => 1584087701,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY87xbM1');
